import SwiftCompilerPlugin
import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

private enum ProofDiagnostic: String, DiagnosticMessage {
  case viewModelRequiresClass
  case viewModelRequiresMainActor
  case stateMustNotUseObservable
  case unrestrictedPublicStateSetter
  case invalidBoundDeclaration
  case invalidBoundPlacement
  case invalidReactionDeclaration
  case invalidReactionPlacement

  var message: String {
    switch self {
    case .viewModelRequiresClass:
      "@ViewModel can only be attached to a class"
    case .viewModelRequiresMainActor:
      "@ViewModel requires the class to be explicitly @MainActor"
    case .stateMustNotUseObservable:
      "State observation is generated by @ViewModel; remove @Observable from State"
    case .unrestrictedPublicStateSetter:
      "public VISOR State fields require private(set)"
    case .invalidBoundDeclaration:
      "@Bound requires one ordinary stored State property and a source selection"
    case .invalidBoundPlacement:
      "@Bound is only supported on a direct member of @ViewModel.State"
    case .invalidReactionDeclaration:
      "@Reaction requires one nonthrowing Void method parameter and a source selection"
    case .invalidReactionPlacement:
      "@Reaction is only supported on a direct @ViewModel member"
    }
  }

  var diagnosticID: MessageID {
    MessageID(domain: "V11CompileProof", id: rawValue)
  }

  var severity: DiagnosticSeverity { .error }
}

private struct UnsupportedStateFieldDiagnostic: DiagnosticMessage {
  enum Kind: String {
    case accessorObservers
    case attribute
    case ignoredIsolationModifier
    case isolationModifier
    case multipleBindings
    case nonIdentifierPattern
    case storageModifier
    case writableComputed
  }

  let kind: Kind
  let detail: String?
  let fieldName: String?

  var message: String {
    switch kind {
    case .accessorObservers:
      "VISOR State field '\(fieldName ?? "<unknown>")' cannot declare willSet or didSet"
    case .attribute:
      "@\(detail ?? "<unknown>") is unsupported on VISOR State field '\(fieldName ?? "<unknown>")'"
    case .ignoredIsolationModifier:
      "VISOR State field '\(fieldName ?? "<unknown>")' cannot combine " +
        "@ObservationIgnored with \(detail ?? "nonisolated")"
    case .isolationModifier:
      "VISOR State field '\(fieldName ?? "<unknown>")' cannot be declared " +
        (detail ?? "nonisolated")
    case .multipleBindings:
      "declare each VISOR State field in a separate var declaration"
    case .nonIdentifierPattern:
      "VISOR State fields require a single identifier pattern"
    case .storageModifier:
      "'\(detail ?? "<unknown>")' is unsupported on VISOR State field '\(fieldName ?? "<unknown>")'"
    case .writableComputed:
      "writable computed VISOR State field '\(fieldName ?? "<unknown>")' is unsupported"
    }
  }

  var diagnosticID: MessageID {
    MessageID(domain: "V11CompileProof", id: kind.rawValue)
  }

  var severity: DiagnosticSeverity { .error }
}

private extension MacroExpansionContext {
  var isDirectViewModelStateContext: Bool {
    let classes = lexicalContext.compactMap { $0.as(ClassDeclSyntax.self) }
    guard classes.count >= 2 else { return false }
    return classes[0].name.text == "State" &&
      classes[1].attributes.contains(named: "ViewModel")
  }

  var isDirectViewModelContext: Bool {
    guard let type = lexicalContext.first?.as(ClassDeclSyntax.self) else {
      return false
    }
    return type.attributes.contains(named: "ViewModel")
  }
}

private enum ProofFixIt: String, FixItMessage {
  case addMainActor
  case restrictStateSetter

  var message: String {
    switch self {
    case .addMainActor:
      "add '@MainActor'"
    case .restrictStateSetter:
      "restrict the State field setter"
    }
  }

  var fixItID: MessageID {
    MessageID(domain: "V11CompileProof", id: rawValue)
  }
}

private extension AttributeListSyntax {
  func attribute(named name: String) -> AttributeSyntax? {
    compactMap { element in
      element.as(AttributeSyntax.self)
    }.first { attribute in
      attribute.attributeName.trimmedDescription
        .split(separator: ".")
        .last == Substring(name)
    }
  }

  func contains(named name: String) -> Bool {
    attribute(named: name) != nil
  }

  func unsupportedStateAttribute(
    allowingGeneratedAttribute: Bool = false
  ) -> AttributeSyntax? {
    compactMap { element -> AttributeSyntax? in
      guard let attribute = element.as(AttributeSyntax.self) else {
        return nil
      }

      let name = attribute.attributeName.trimmedDescription
        .split(separator: ".")
        .last
      if name == "ObservationIgnored" {
        return nil
      }
      if name == "Bound" {
        return nil
      }
      if allowingGeneratedAttribute && name == "_ViewModelStateField" {
        return nil
      }
      return attribute
    }.first
  }
}

private extension DeclModifierListSyntax {
  var exportedPrefix: String {
    let getterModifiers = filter { modifier in
      modifier.detail?.detail.text != "set"
    }

    if getterModifiers.contains(where: {
      $0.name.text == "public" || $0.name.text == "open"
    }) {
      return "public "
    }
    if getterModifiers.contains(where: { $0.name.text == "package" }) {
      return "package "
    }
    if getterModifiers.contains(where: { $0.name.text == "fileprivate" }) {
      return "fileprivate "
    }
    if getterModifiers.contains(where: { $0.name.text == "private" }) {
      return "private "
    }
    return ""
  }

  var hasTypeStorageModifier: Bool {
    contains { modifier in
      modifier.name.text == "static" || modifier.name.text == "class"
    }
  }

  var hasPublicGetter: Bool {
    contains { modifier in
      modifier.detail?.detail.text != "set" &&
        (modifier.name.text == "public" || modifier.name.text == "open")
    }
  }

  var hasPrivateSetter: Bool {
    contains { modifier in
      modifier.name.text == "private" && modifier.detail?.detail.text == "set"
    }
  }
}

private extension PatternBindingSyntax {
  var isGetOnlyComputedProperty: Bool {
    guard let accessorBlock else { return false }

    switch accessorBlock.accessors {
    case .getter:
      return true
    case let .accessors(accessors):
      return accessors.allSatisfy { accessor in
        accessor.accessorSpecifier.text == "get"
      }
    }
  }

  var hasStateAccessorObservers: Bool {
    guard
      let accessorBlock,
      case let .accessors(accessors) = accessorBlock.accessors
    else {
      return false
    }

    return accessors.contains { accessor in
      let specifier = accessor.accessorSpecifier.text
      return specifier == "willSet" || specifier == "didSet"
    }
  }
}

private extension VariableDeclSyntax {
  var stateIsolationModifier: DeclModifierSyntax? {
    modifiers.first { modifier in
      modifier.name.text == "nonisolated"
    }
  }

  var isIgnoredStateDeclaration: Bool {
    bindingSpecifier.text == "let" ||
      modifiers.hasTypeStorageModifier ||
      attributes.contains(named: "ObservationIgnored") ||
      (bindings.count == 1 && bindings.first?.isGetOnlyComputedProperty == true)
  }

  func unsupportedStateFieldDiagnostic(
    allowingGeneratedAttribute: Bool = false
  ) -> UnsupportedStateFieldDiagnostic? {
    if
      bindingSpecifier.text == "var",
      !modifiers.hasTypeStorageModifier,
      attributes.contains(named: "ObservationIgnored"),
      bindings.count == 1,
      let binding = bindings.first,
      !binding.isGetOnlyComputedProperty,
      let identifier = binding.pattern.as(IdentifierPatternSyntax.self),
      let modifier = stateIsolationModifier
    {
      return UnsupportedStateFieldDiagnostic(
        kind: .ignoredIsolationModifier,
        detail: modifier.trimmedDescription,
        fieldName: identifier.identifier.text)
    }

    guard !isIgnoredStateDeclaration else { return nil }

    guard bindings.count == 1 else {
      return UnsupportedStateFieldDiagnostic(
        kind: .multipleBindings,
        detail: nil,
        fieldName: nil)
    }

    guard let binding = bindings.first else {
      return UnsupportedStateFieldDiagnostic(
        kind: .multipleBindings,
        detail: nil,
        fieldName: nil)
    }

    guard let identifier = binding.pattern.as(IdentifierPatternSyntax.self) else {
      return UnsupportedStateFieldDiagnostic(
        kind: .nonIdentifierPattern,
        detail: nil,
        fieldName: nil)
    }
    let fieldName = identifier.identifier.text

    if binding.hasStateAccessorObservers {
      return UnsupportedStateFieldDiagnostic(
        kind: .accessorObservers,
        detail: nil,
        fieldName: fieldName)
    }

    if binding.accessorBlock != nil {
      return UnsupportedStateFieldDiagnostic(
        kind: .writableComputed,
        detail: nil,
        fieldName: fieldName)
    }

    if let modifier = stateIsolationModifier {
      return UnsupportedStateFieldDiagnostic(
        kind: .isolationModifier,
        detail: modifier.trimmedDescription,
        fieldName: fieldName)
    }

    if let modifier = modifiers.first(where: { modifier in
      ["lazy", "weak", "unowned"].contains(modifier.name.text)
    }) {
      return UnsupportedStateFieldDiagnostic(
        kind: .storageModifier,
        detail: modifier.name.text,
        fieldName: fieldName)
    }

    if let attribute = attributes.unsupportedStateAttribute(
      allowingGeneratedAttribute: allowingGeneratedAttribute
    ) {
      let attributeName = attribute.attributeName.trimmedDescription
        .split(separator: ".")
        .last
        .map(String.init)
      return UnsupportedStateFieldDiagnostic(
        kind: .attribute,
        detail: attributeName,
        fieldName: fieldName)
    }

    return nil
  }
}

private extension ClassDeclSyntax {
  var hasUnsupportedStateField: Bool {
    memberBlock.members.contains { member in
      member.decl.as(VariableDeclSyntax.self)?
        .unsupportedStateFieldDiagnostic() != nil
    }
  }
}

private struct StateField {
  let declaration: VariableDeclSyntax
  let binding: PatternBindingSyntax
  let name: String

  var accessPrefix: String {
    declaration.modifiers.exportedPrefix
  }

  var typeText: String {
    binding.typeAnnotation.map { ": \($0.type.trimmedDescription)" } ?? ""
  }

  var initializerText: String {
    binding.initializer.map { " = \($0.value.trimmedDescription)" } ?? ""
  }
}

private func stateField(
  from declaration: some DeclSyntaxProtocol,
  allowingObservationIgnored: Bool = false
) -> StateField? {
  guard
    let variable = declaration.as(VariableDeclSyntax.self),
    variable.bindingSpecifier.text == "var",
    !variable.modifiers.hasTypeStorageModifier,
    variable.unsupportedStateFieldDiagnostic(
      allowingGeneratedAttribute: allowingObservationIgnored) == nil,
    variable.bindings.count == 1,
    let binding = variable.bindings.first,
    binding.accessorBlock == nil,
    let identifier = binding.pattern.as(IdentifierPatternSyntax.self),
    !identifier.identifier.text.hasPrefix("_visor"),
    allowingObservationIgnored ||
      !variable.attributes.contains(named: "ObservationIgnored")
  else {
    return nil
  }

  return StateField(
    declaration: variable,
    binding: binding,
    name: identifier.identifier.text)
}

private struct ObservationSelection {
  let source: ExprSyntax
  let selection: ExprSyntax?
}

private extension AttributeSyntax {
  var observationSelection: ObservationSelection? {
    guard let arguments = arguments?.as(LabeledExprListSyntax.self) else {
      return nil
    }
    guard let source = arguments.first(where: {
      $0.label?.text == "source"
    })?.expression else {
      return nil
    }
    let selection = arguments.first(where: {
      $0.label?.text == "selecting"
    })?.expression
    return ObservationSelection(source: source, selection: selection)
  }
}

private struct BoundRecipeEntry {
  let source: ExprSyntax
  let selection: ExprSyntax?
  let fieldName: String
}

private struct ReactionRecipeEntry {
  let source: ExprSyntax
  let selection: ExprSyntax?
  let methodName: String
  let argumentLabel: String?
  let isAsync: Bool
}

private struct ObservationRecipeGroup {
  let source: ExprSyntax
  var bounds: [BoundRecipeEntry] = []
  var reactions: [ReactionRecipeEntry] = []
}

public struct ViewModelMacro: MemberMacro, MemberAttributeMacro, ExtensionMacro {
  public static func expansion(
    of _: AttributeSyntax,
    providingMembersOf declaration: some DeclGroupSyntax,
    conformingTo _: [TypeSyntax],
    in _: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    guard let viewModel = declaration.as(ClassDeclSyntax.self) else {
      return []
    }
    guard viewModel.attributes.contains(named: "MainActor") else {
      return []
    }
    if viewModel.memberBlock.members.contains(where: { member in
      guard
        let state = member.decl.as(ClassDeclSyntax.self),
        state.name.text == "State"
      else {
        return false
      }
      return state.attributes.contains(named: "Observable")
    }) {
      return []
    }

    if viewModel.memberBlock.members.contains(where: { member in
      guard
        let state = member.decl.as(ClassDeclSyntax.self),
        state.name.text == "State"
      else {
        return false
      }
      return state.hasUnsupportedStateField
    }) {
      return []
    }

    var groups: [ObservationRecipeGroup] = []

    func groupIndex(for source: ExprSyntax) -> Int {
      let spelling = source.trimmedDescription
      if let index = groups.firstIndex(where: {
        $0.source.trimmedDescription == spelling
      }) {
        return index
      }
      groups.append(ObservationRecipeGroup(source: source))
      return groups.index(before: groups.endIndex)
    }

    if let state = viewModel.memberBlock.members.compactMap({
      $0.decl.as(ClassDeclSyntax.self)
    }).first(where: { $0.name.text == "State" }) {
      for member in state.memberBlock.members {
        guard
          let variable = member.decl.as(VariableDeclSyntax.self),
          let bound = variable.attributes.attribute(named: "Bound"),
          let observation = bound.observationSelection,
          let binding = variable.bindings.first,
          let identifier = binding.pattern.as(IdentifierPatternSyntax.self)
        else {
          continue
        }
        let entry = BoundRecipeEntry(
          source: observation.source,
          selection: observation.selection,
          fieldName: identifier.identifier.text)
        groups[groupIndex(for: observation.source)].bounds.append(entry)
      }
    }

    for member in viewModel.memberBlock.members {
      guard
        let function = member.decl.as(FunctionDeclSyntax.self),
        let reaction = function.attributes.attribute(named: "Reaction"),
        let observation = reaction.observationSelection,
        let parameter = function.signature.parameterClause.parameters.first,
        function.signature.parameterClause.parameters.count == 1
      else {
        continue
      }
      let label = parameter.firstName.text == "_"
        ? nil
        : parameter.firstName.text
      let entry = ReactionRecipeEntry(
        source: observation.source,
        selection: observation.selection,
        methodName: function.name.text,
        argumentLabel: label,
        isAsync: function.signature.effectSpecifiers?.asyncSpecifier != nil)
      groups[groupIndex(for: observation.source)].reactions.append(entry)
    }

    let prefix = viewModel.modifiers.exportedPrefix
    let ownership: DeclSyntax = DeclSyntax(stringLiteral:
      "\(prefix)let _visorObservationOwnership = " +
      "VISOR._ViewModelObservationOwnership()")

    guard !groups.isEmpty else { return [ownership] }

    let recipes = groups.map { group in
      let projections = group.bounds.map { bound in
        let value = bound.selection.map {
          "snapshot[keyPath: \($0.trimmedDescription)]"
        } ?? "snapshot"
        return """
          { [weak self] snapshot in
            guard let self else { return }
            self.updateState(\\.\(bound.fieldName), to: \(value))
          }
          """
      }.joined(separator: ",\n")

      let reactions = group.reactions.map { reaction in
        let value = reaction.selection.map {
          "snapshot[keyPath: \($0.trimmedDescription)]"
        } ?? "snapshot"
        let argument = reaction.argumentLabel.map {
          "\($0): \(value)"
        } ?? value
        let awaitPrefix = reaction.isAsync ? "await " : ""
        return """
          { [weak self] snapshot in
            guard let self else { return }
            \(awaitPrefix)self.\(reaction.methodName)(\(argument))
          }
          """
      }.joined(separator: ",\n")

      return """
        visitor.add(
          source: self[keyPath: \(group.source.trimmedDescription)],
          projections: [
            \(projections)
          ],
          initialReactions: [
            \(reactions)
          ])
        """
    }.joined(separator: "\n")

    return [ownership, DeclSyntax(stringLiteral: """
      \(prefix)func _visorBuildObservationRecipe(
        into visitor: VISOR._ObservationRecipeVisitor
      ) {
        \(recipes)
      }
      """)]
  }

  public static func expansion(
    of _: AttributeSyntax,
    attachedTo declaration: some DeclGroupSyntax,
    providingAttributesFor member: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [AttributeSyntax] {
    guard
      let state = member.as(ClassDeclSyntax.self),
      state.name.text == "State"
    else {
      return []
    }

    guard
      let viewModel = declaration.as(ClassDeclSyntax.self),
      viewModel.attributes.contains(named: "MainActor")
    else {
      return []
    }

    guard let observable = state.attributes.attribute(named: "Observable") else {
      var attributes: [AttributeSyntax] = ["@VISOR._ViewModelState"]
      if !state.attributes.contains(named: "MainActor") {
        attributes.insert("@MainActor", at: 0)
      }
      return attributes
    }

    context.diagnose(Diagnostic(
      node: Syntax(observable),
      message: ProofDiagnostic.stateMustNotUseObservable))
    return []
  }

  public static func expansion(
    of _: AttributeSyntax,
    attachedTo declaration: some DeclGroupSyntax,
    providingExtensionsOf type: some TypeSyntaxProtocol,
    conformingTo _: [TypeSyntax],
    in context: some MacroExpansionContext
  ) throws -> [ExtensionDeclSyntax] {
    guard let viewModel = declaration.as(ClassDeclSyntax.self) else {
      context.diagnose(Diagnostic(
        node: Syntax(declaration),
        message: ProofDiagnostic.viewModelRequiresClass))
      return []
    }
    guard viewModel.attributes.contains(named: "MainActor") else {
      let position = viewModel.positionAfterSkippingLeadingTrivia
      context.diagnose(Diagnostic(
        node: Syntax(viewModel.name),
        message: ProofDiagnostic.viewModelRequiresMainActor,
        fixIts: [
          FixIt(
            message: ProofFixIt.addMainActor,
            changes: [
              .replaceText(
                range: position..<position,
                with: "@MainActor\n",
                in: Syntax(viewModel)),
            ])
        ]))
      return []
    }
    if viewModel.memberBlock.members.contains(where: { member in
      guard
        let state = member.decl.as(ClassDeclSyntax.self),
        state.name.text == "State"
      else {
        return false
      }
      return state.attributes.contains(named: "Observable")
    }) {
      return []
    }
    if viewModel.memberBlock.members.contains(where: { member in
      guard
        let state = member.decl.as(ClassDeclSyntax.self),
        state.name.text == "State"
      else {
        return false
      }
      return state.hasUnsupportedStateField
    }) {
      return []
    }
    return [try ExtensionDeclSyntax("extension \(type): VISOR.ViewModel {}")]
  }
}

/// Minimal Stage E `@LazyViewModel` bridge. The consumer supplies a
/// `makeViewModel` closure and `content`.
/// Generated code owns the ViewModel lazily and delegates the entire
/// observation lifetime to VISOR's SwiftUI host.
public struct LazyViewModelMacro: MemberMacro {
  public static func expansion(
    of attribute: AttributeSyntax,
    providingMembersOf declaration: some DeclGroupSyntax,
    conformingTo _: [TypeSyntax],
    in _: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    guard
      let view = declaration.as(StructDeclSyntax.self),
      let arguments = attribute.arguments?.as(LabeledExprListSyntax.self),
      let first = arguments.first
    else {
      return []
    }

    let metatype = first.expression.trimmedDescription
    guard metatype.hasSuffix(".self") else { return [] }
    let viewModelType = String(metatype.dropLast(".self".count))
    let validPolicies = [
      "alwaysObserving",
      "pauseInBackground",
      "pauseWhenInactive",
    ]
    let policy: String
    if arguments.count > 1 {
      let index = arguments.index(after: arguments.startIndex)
      let spelling = arguments[index].expression.trimmedDescription
      guard
        let selected = spelling.split(separator: ".").last.map(String.init),
        validPolicies.contains(selected)
      else {
        return []
      }
      policy = selected
    } else {
      policy = "alwaysObserving"
    }
    let prefix = view.modifiers.exportedPrefix

    return [
      """
      @SwiftUI.State private var _viewModel: \(raw: viewModelType)?
      """,
      """
      \(raw: prefix)var viewModel: \(raw: viewModelType) {
        guard let viewModel = _viewModel else {
          preconditionFailure(
            "@LazyViewModel content is unavailable before initialisation")
        }
        return viewModel
      }
      """,
      """
      \(raw: prefix)var state: \(raw: viewModelType).State {
        viewModel.state
      }
      """,
      """
      \(raw: prefix)var body: some SwiftUI.View {
        SwiftUI.Group {
          if let viewModel = _viewModel {
            VISOR._visorOwnedViewModelContent(
              for: viewModel,
              observationPolicy: VISOR.ObservationPolicy.\(raw: policy)
            ) { _ in
              content
            }
          } else {
            SwiftUI.Color.clear
          }
        }
        .task {
          if _viewModel == nil {
            _viewModel = makeViewModel()
          }
        }
      }
      """,
    ]
  }
}

public struct BoundMacro: PeerMacro {
  public static func expansion(
    of attribute: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    guard context.isDirectViewModelStateContext else {
      context.diagnose(Diagnostic(
        node: Syntax(declaration),
        message: ProofDiagnostic.invalidBoundPlacement))
      return []
    }
    guard
      let variable = declaration.as(VariableDeclSyntax.self),
      variable.unsupportedStateFieldDiagnostic() == nil,
      stateField(from: variable) != nil,
      attribute.observationSelection != nil
    else {
      context.diagnose(Diagnostic(
        node: Syntax(declaration),
        message: ProofDiagnostic.invalidBoundDeclaration))
      return []
    }
    return []
  }
}

public struct ReactionMacro: PeerMacro {
  public static func expansion(
    of attribute: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    guard context.isDirectViewModelContext else {
      context.diagnose(Diagnostic(
        node: Syntax(declaration),
        message: ProofDiagnostic.invalidReactionPlacement))
      return []
    }
    guard
      let function = declaration.as(FunctionDeclSyntax.self),
      function.signature.parameterClause.parameters.count == 1,
      function.signature.returnClause == nil,
      function.signature.effectSpecifiers?.throwsClause == nil,
      !function.modifiers.hasTypeStorageModifier,
      attribute.observationSelection != nil
    else {
      context.diagnose(Diagnostic(
        node: Syntax(declaration),
        message: ProofDiagnostic.invalidReactionDeclaration))
      return []
    }
    return []
  }
}

public struct ViewModelStateMacro:
  MemberMacro,
  MemberAttributeMacro,
  ExtensionMacro
{
  public static func expansion(
    of _: AttributeSyntax,
    providingMembersOf declaration: some DeclGroupSyntax,
    conformingTo _: [TypeSyntax],
    in _: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    guard let state = declaration.as(ClassDeclSyntax.self) else { return [] }
    guard !state.hasUnsupportedStateField else { return [] }

    let fields = state.memberBlock.members.compactMap { member in
      stateField(from: member.decl)
    }
    let prefix = state.modifiers.exportedPrefix

    let fieldDescriptors: [DeclSyntax] = fields.map { field in
      """
      private static let _visorField_\(raw: field.name) = VISOR._StateField(
        "\(raw: field.name)",
        keyPath: \\State.\(raw: field.name))
      """
    }

    let selectorMembers = fields.compactMap { field -> String? in
      // A private member of the nested carrier is inaccessible even from its
      // enclosing State. Private fields remain accessor-instrumented but do
      // not receive an unusable routed selector.
      guard field.accessPrefix != "private " else { return nil }
      return "\(field.accessPrefix)let \(field.name) = State._visorField_\(field.name)"
    }.joined(separator: "\n")

    let selectors: DeclSyntax = """
      @MainActor
      \(raw: prefix)struct _VISORSelectors {
        \(raw: selectorMembers)

        \(raw: prefix)init() {}
      }
      """

    let recorder: DeclSyntax = """
      \(raw: prefix)var _visorMutationRecorder: (any VISOR._StateMutationRecorder)?
      """

    let registrar: DeclSyntax = """
      private let _$observationRegistrar = Observation.ObservationRegistrar()
      """

    let access: DeclSyntax = """
      nonisolated func access<Member>(
        keyPath: KeyPath<State, Member>
      ) {
        _$observationRegistrar.access(self, keyPath: keyPath)
      }
      """

    let withMutation: DeclSyntax = """
      nonisolated func withMutation<Member, MutationResult>(
        keyPath: KeyPath<State, Member>,
        _ mutation: () throws -> MutationResult
      ) rethrows -> MutationResult {
        try _$observationRegistrar.withMutation(
          of: self,
          keyPath: keyPath,
          mutation)
      }
      """

    let selectorRoot: DeclSyntax = """
      @MainActor
      \(raw: prefix)static let _visorSelectors = _VISORSelectors()
      """

    let allFieldMembers = fields.map { field in
      "VISOR._AnyStateField(_visorField_\(field.name), untrackedRead: { $0._\(field.name) })"
    }.joined(separator: ",\n")

    let allFields: DeclSyntax = """
      @MainActor
      \(raw: prefix)static let _visorAllFields: [VISOR._AnyStateField<State>] = [
        \(raw: allFieldMembers)
      ]
      """

    let genericComparison: DeclSyntax = """
      private nonisolated func _visorShouldNotifyObservers<Value>(
        _ lhs: Value,
        _ rhs: Value
      ) -> Bool {
        true
      }
      """

    let equatableComparison: DeclSyntax = """
      private nonisolated func _visorShouldNotifyObservers<Value: Equatable>(
        _ lhs: Value,
        _ rhs: Value
      ) -> Bool {
        lhs != rhs
      }
      """

    let referenceComparison: DeclSyntax = """
      private nonisolated func _visorShouldNotifyObservers<Value: AnyObject>(
        _ lhs: Value,
        _ rhs: Value
      ) -> Bool {
        lhs !== rhs
      }
      """

    let equatableReferenceComparison: DeclSyntax = """
      private nonisolated func _visorShouldNotifyObservers<
        Value: Equatable & AnyObject
      >(
        _ lhs: Value,
        _ rhs: Value
      ) -> Bool {
        lhs != rhs
      }
      """

    return [
      registrar,
      access,
      withMutation,
      recorder,
    ] + fieldDescriptors + [
      selectors,
      selectorRoot,
      allFields,
      genericComparison,
      equatableComparison,
      referenceComparison,
      equatableReferenceComparison,
    ]
  }

  public static func expansion(
    of _: AttributeSyntax,
    attachedTo declaration: some DeclGroupSyntax,
    providingAttributesFor member: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [AttributeSyntax] {
    guard let state = declaration.as(ClassDeclSyntax.self) else { return [] }

    if let variable = member.as(VariableDeclSyntax.self),
      !variable.attributes.contains(named: "Bound"),
      let diagnostic = variable.unsupportedStateFieldDiagnostic()
    {
      context.diagnose(Diagnostic(
        node: Syntax(variable),
        message: diagnostic))
      return []
    }

    // Declaration synthesis is fail-closed. One rejected field prevents every
    // sibling from receiving accessors, descriptors or a partial State
    // conformance while still allowing the rejected member to diagnose once.
    guard !state.hasUnsupportedStateField else { return [] }

    guard let field = stateField(from: member) else { return [] }

    if
      field.declaration.modifiers.hasPublicGetter,
      !field.declaration.modifiers.hasPrivateSetter
    {
      let position = field.declaration.bindingSpecifier.position
      context.diagnose(Diagnostic(
        node: Syntax(field.declaration),
        message: ProofDiagnostic.unrestrictedPublicStateSetter,
        fixIts: [
          FixIt(
            message: ProofFixIt.restrictStateSetter,
            changes: [
              .replaceText(
                range: position..<position,
                with: "private(set) ",
                in: Syntax(field.declaration)),
            ])
        ]))
    }

    return [
      "@VISOR._ViewModelStateField",
    ]
  }

  public static func expansion(
    of _: AttributeSyntax,
    attachedTo declaration: some DeclGroupSyntax,
    providingExtensionsOf type: some TypeSyntaxProtocol,
    conformingTo _: [TypeSyntax],
    in _: some MacroExpansionContext
  ) throws -> [ExtensionDeclSyntax] {
    guard
      let state = declaration.as(ClassDeclSyntax.self),
      !state.hasUnsupportedStateField
    else {
      return []
    }
    return [
      try ExtensionDeclSyntax(
        "extension \(type): nonisolated Observation.Observable {}"),
      try ExtensionDeclSyntax(
        "extension \(type): VISOR._ViewModelState {}"),
    ]
  }
}

public struct ViewModelStateFieldMacro: AccessorMacro, PeerMacro {
  public static func expansion(
    of _: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in _: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    guard let field = stateField(
      from: declaration,
      allowingObservationIgnored: true
    ) else { return [] }

    return ["""
      private var _\(raw: field.name)\(raw: field.typeText)\(raw: field.initializerText)
      """]
  }

  public static func expansion(
    of _: AttributeSyntax,
    providingAccessorsOf declaration: some DeclSyntaxProtocol,
    in _: some MacroExpansionContext
  ) throws -> [AccessorDeclSyntax] {
    guard let field = stateField(
      from: declaration,
      allowingObservationIgnored: true
    ) else { return [] }
    let name = field.name

    let initialiser: AccessorDeclSyntax = """
      @storageRestrictions(initializes: _\(raw: name))
      init(initialValue) {
        _\(raw: name) = initialValue
      }
      """

    let getter: AccessorDeclSyntax = """
      get {
        access(keyPath: \\.\(raw: name))
        return _\(raw: name)
      }
      """

    let setter: AccessorDeclSyntax = """
      set {
        guard _visorMutationRecorder != nil else {
          if _visorShouldNotifyObservers(_\(raw: name), newValue) {
            withMutation(keyPath: \\.\(raw: name)) {
              _\(raw: name) = newValue
            }
          } else {
            _\(raw: name) = newValue
          }
          return
        }

        let oldValue = _\(raw: name)
        if _visorShouldNotifyObservers(_\(raw: name), newValue) {
          withMutation(keyPath: \\.\(raw: name)) {
            _\(raw: name) = newValue
          }
        } else {
          _\(raw: name) = newValue
        }
        let resultingValue = _\(raw: name)
        _visorRecordMutation(
          Self._visorField_\(raw: name),
          oldValue: oldValue,
          newValue: resultingValue)
      }
      """

    let modify: AccessorDeclSyntax = """
      _modify {
        access(keyPath: \\.\(raw: name))

        guard _visorMutationRecorder != nil else {
          _$observationRegistrar.willSet(self, keyPath: \\.\(raw: name))
          defer {
            _$observationRegistrar.didSet(self, keyPath: \\.\(raw: name))
          }
          yield &_\(raw: name)
          return
        }

        let oldValue = _\(raw: name)
        _$observationRegistrar.willSet(self, keyPath: \\.\(raw: name))
        defer {
          _$observationRegistrar.didSet(self, keyPath: \\.\(raw: name))
          _visorRecordMutation(
            Self._visorField_\(raw: name),
            oldValue: oldValue,
            newValue: _\(raw: name))
        }
        yield &_\(raw: name)
      }
      """

    return [
      initialiser,
      getter,
      setter,
      modify,
    ]
  }
}

@main
struct V11CompileProofPlugin: CompilerPlugin {
  let providingMacros: [Macro.Type] = [
    BoundMacro.self,
    LazyViewModelMacro.self,
    ReactionMacro.self,
    ViewModelMacro.self,
    ViewModelStateMacro.self,
    ViewModelStateFieldMacro.self,
  ]
}
