/// Selects the name of the observation sequence generated by
/// ``ObservationState()``.
///
/// Complete domain State normally uses ``snapshots``. Use ``values`` when the
/// State is genuinely scalar, or ``named(_:)`` when a domain-specific plural
/// communicates the sequence more clearly.
public enum ObservationStateSequenceName: Sendable {
  /// Generates `<property>Snapshots`.
  case snapshots

  /// Generates `<property>Values`.
  case values

  /// Generates the member named by a static Swift identifier.
  case named(StaticString)
}

/// Synthesises the read-only sequence requirements declared by
/// ``ObservationState(initial:)`` properties in a protocol.
///
/// Swift requires protocol members to be introduced by a type-level member
/// macro so their existential witness layout is complete. Concrete classes and
/// actors do not use this annotation.
@attached(member, names: arbitrary)
public macro ObservationStateRequirements() = #externalMacro(
  module: "VISORMacros",
  type: "ObservationStateRequirementsMacro")

/// Declares producer-owned State whose assignments are observable.
///
/// The declared property remains the producer's canonical mutable State.
/// Assigning it synchronously replaces the current snapshot and publishes that
/// snapshot to the generated read-only sequence:
///
/// ```swift
/// @ObservationState
/// public private(set) var playback: PlaybackSnapshot = .stopped
///
/// func stop() {
///   playback = .stopped
/// }
///
/// for try await snapshot in service.playbackSnapshots {
///   // Receives the current snapshot, then each replacement.
/// }
/// ```
///
/// By default the generated sequence is named `<property>Snapshots`. Select
/// `observedAs: .values` for genuinely scalar State, or provide a rare
/// domain-specific plural with `observedAs: .named("permissionStatuses")`.
/// The sequence is nonisolated because it is read-only, `Sendable`, and
/// lock-backed; obtaining it never requires a hop to the producer's actor.
/// The State type may be written explicitly or be syntactically evident from a
/// nominal initialiser, static member, collection initialiser, or primitive
/// literal. Add an explicit annotation when an initialiser is ambiguous, such
/// as a factory function whose return type is not present in its spelling.
///
/// A protocol requirement may supply `initial:` as test-double metadata.
/// `@ObservationStateRequirements` generates the corresponding read-only
/// sequence requirement. `@GenerateStub` and `@GenerateSpy` use an explicit
/// initial value, `@DefaultValue`, or a known standard default for their mutable
/// State:
///
/// ```swift
/// @GenerateSpy
/// @ObservationStateRequirements
/// protocol PlaybackService {
///   @ObservationState(initial: PlaybackSnapshot.stopped)
///   var playback: PlaybackSnapshot { get }
/// }
///
/// let spy = SpyPlaybackService()
/// spy.playback = .playing
/// // spy.playbackSnapshots publishes .playing automatically.
/// ```
///
/// Prefer one observation State value over several independently published
/// fields when those fields form one coherent domain revision. Keep an
/// explicit ``ObservationChannel`` for classes whose initialiser can throw
/// before initialisation completes; current Swift toolchains can miscompile
/// partial cleanup for macro-owned storage in that case.
///
/// If the enclosing type also uses `@Observable`, place
/// `@ObservationIgnored` immediately below `@ObservationState`. The compiler
/// expands both macros from the authored declaration, so they would otherwise
/// both try to provide its accessors. `@ObservationState` still registers the
/// scalar's reads and mutations with Apple Observation.
@attached(
  accessor,
  names: named(init), named(get), named(set))
@attached(peer, names: arbitrary)
public macro ObservationState() = #externalMacro(
  module: "VISORMacros",
  type: "ObservationStateMacro")

/// Declares observable State and selects its generated sequence name.
///
/// - Parameter naming: The naming convention for the generated source property.
@attached(
  accessor,
  names: named(init), named(get), named(set))
@attached(peer, names: arbitrary)
public macro ObservationState(
  observedAs naming: ObservationStateSequenceName
) = #externalMacro(
  module: "VISORMacros",
  type: "ObservationStateMacro")

/// Marks a protocol State requirement and supplies its test-double baseline.
///
/// Protocol requirements cannot contain a stored initial value. Concrete
/// classes and actors initialise their scalar normally and do not use this
/// overload.
///
/// - Parameter initial: The baseline used by generated test doubles.
@attached(peer, names: arbitrary)
public macro ObservationState<Value: Sendable>(
  initial: Value
) = #externalMacro(
  module: "VISORMacros",
  type: "ObservationStateRequirementMacro")

/// Marks a protocol State requirement with a test-double baseline and selects
/// its generated sequence name.
///
/// - Parameters:
///   - initial: The baseline used by generated test doubles.
///   - naming: The naming convention for the generated source property.
@attached(peer, names: arbitrary)
public macro ObservationState<Value: Sendable>(
  initial: Value,
  observedAs naming: ObservationStateSequenceName
) = #externalMacro(
  module: "VISORMacros",
  type: "ObservationStateRequirementMacro")
