import SwiftUI

// MARK: - _LazyViewModelContent

/// The stable content slot generated by `@LazyViewModel`. Presentation state
/// can outlive a retained callback; only this mounted host retains the lifetime.
@MainActor
private struct _LazyViewModelContent<VM: ViewModel, Content: View, Pending: View, Failure: View>: View {

  // MARK: Internal

  let presentation: _LazyViewModelPresentation<VM>
  let observationPolicy: ObservationPolicy
  let pending: () -> Pending
  let failure: () -> Failure
  let ready: (VM, ViewModelBindings<VM>) -> Content

  var body: some View {
    Group {
      if !isEnabled {
        Color.clear
      } else if let model = presentation.readyModel(isEnabled: isEnabled) {
        ready(model, presentation.readyBindings(for: model))
      } else if presentation.owner?._visorFailure != nil {
        failure()
      } else {
        pending()
      }
    }
    .task {
      guard lifetime == nil, !Task.isCancelled else { return }
      let model = presentation.prepare(factory: factory, router: router)
      let lifetime = _ViewModelObservationLifetime(viewModel: model, initiallyEnabled: isEnabled)
      self.lifetime = lifetime
      presentation.owner = lifetime.owner
    }
    .onAppear {
      guard let lifetime else { return }
      presentation.restoreOwner(lifetime.owner, isEnabled: isEnabled)
    }
    .onChange(of: isEnabled) { _, enabled in
      lifetime?.owner._visorSetEnabled(enabled)
    }
  }

  // MARK: Private

  @State private var lifetime: _ViewModelObservationLifetime<VM>?
  @Environment(\.scenePhase) private var scenePhase
  @Environment(ViewModelFactory<VM>.self) private var factory
  @Environment(\._visorRouter) private var router

  private var isEnabled: Bool {
    observationPolicy._visorIsEnabled(in: scenePhase)
  }
}

/// Opaque bridge used by downstream macro expansions. It exposes presentation
/// values without exposing observation ownership or lifecycle controls.
@MainActor
public func _visorLazyViewModelContent<VM: ViewModel>(
  presentation: _LazyViewModelPresentation<VM>,
  observationPolicy: ObservationPolicy,
  @ViewBuilder pending: @escaping () -> some View,
  @ViewBuilder failure: @escaping () -> some View,
  @ViewBuilder ready: @escaping (VM, ViewModelBindings<VM>) -> some View,
) -> some View {
  _LazyViewModelContent(
    presentation: presentation,
    observationPolicy: observationPolicy,
    pending: pending,
    failure: failure,
    ready: ready,
  )
}
