import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros
import Testing
@testable import V11CompileProofMacros

private let viewModelMacro: [String: Macro.Type] = [
  "ViewModel": ViewModelMacro.self,
]

private let stateShapeMacro: [String: Macro.Type] = [
  "StateShape": ViewModelStateMacro.self,
]

/// Exercises only the member-policy role of `_ViewModelState` so these tests
/// remain focused on diagnostics instead of snapshotting unrelated synthesis.
private struct StateFieldPolicyMacro: MemberAttributeMacro {
  static func expansion(
    of node: AttributeSyntax,
    attachedTo declaration: some DeclGroupSyntax,
    providingAttributesFor member: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [AttributeSyntax] {
    _ = try ViewModelStateMacro.expansion(
      of: node,
      attachedTo: declaration,
      providingAttributesFor: member,
      in: context)
    return []
  }
}

private let stateFieldPolicyMacro: [String: Macro.Type] = [
  "StateFieldPolicy": StateFieldPolicyMacro.self,
]

private let sourceEntryMacros: [String: Macro.Type] = [
  "Bound": BoundMacro.self,
  "Reaction": ReactionMacro.self,
]

@Suite("V11 macro diagnostics")
struct ViewModelMacroDiagnosticTests {
  @Test
  func `@ViewModel requires explicit main-actor isolation`() {
    assertMacroExpansion(
      """
      @ViewModel
      final class ExampleViewModel {
        final class State {}
      }
      """,
      expandedSource: """
      final class ExampleViewModel {
        final class State {}
      }
      """,
      diagnostics: [
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "viewModelRequiresMainActor"),
          message: "@ViewModel requires the class to be explicitly @MainActor",
          line: 2,
          column: 13,
          severity: .error,
          fixIts: [
            FixItSpec(message: "add '@MainActor'"),
          ]),
      ],
      macros: viewModelMacro,
      applyFixIts: ["add '@MainActor'"],
      fixedSource: """
      @MainActor
      @ViewModel
      final class ExampleViewModel {
        final class State {}
      }
      """)
  }

  @Test(arguments: ["@Observable", "@Observation.Observable"])
  func `Nested State must not stack Observation's macro`(_ observableAttribute: String) {
    let source = """
      @MainActor
      @ViewModel
      final class ExampleViewModel {
        \(observableAttribute)
        final class State {}
      }
      """

    let expandedSource = """
      @MainActor
      final class ExampleViewModel {
        \(observableAttribute)
        final class State {}
      }
      """

    assertMacroExpansion(
      source,
      expandedSource: expandedSource,
      diagnostics: [
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "stateMustNotUseObservable"),
          message: "State observation is generated by @ViewModel; remove @Observable from State",
          line: 4,
          column: 3,
          severity: .error),
      ],
      macros: viewModelMacro)
  }

  @Test
  func `Public State fields require a restricted setter`() {
    assertMacroExpansion(
      """
      @StateFieldPolicy
      final class State {
        public var count = 0
      }
      """,
      expandedSource: """
      final class State {
        public var count = 0
      }
      """,
      diagnostics: [
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "unrestrictedPublicStateSetter"),
          message: "public VISOR State fields require private(set)",
          line: 3,
          column: 3,
          severity: .error,
          fixIts: [
            FixItSpec(message: "restrict the State field setter"),
          ]),
      ],
      macros: stateFieldPolicyMacro,
      applyFixIts: ["restrict the State field setter"],
      fixedSource: """
      @StateFieldPolicy
      final class State {
        public private(set) var count = 0
      }
      """)
  }

  @Test
  func `Supported State visibility and ignored declarations remain valid`() {
    assertMacroExpansion(
      """
      @StateFieldPolicy
      final class State {
        public private(set) var publicValue = 0
        package var packageValue = 0
        var internalValue = 0
        fileprivate var fileValue = 0
        private var privateValue = 0
        var identifier: String
        let constant = 0
        static var shared = 0
        class var sharedDefault: Int { shared }
        @ObservationIgnored var ignored = 0
        var derived: Int { internalValue }
        @ObservationIgnored nonisolated let ignoredConstant = 0
        @ObservationIgnored nonisolated static var ignoredShared = 0
        @ObservationIgnored nonisolated class var ignoredSharedDefault: Int { ignoredShared }
        @ObservationIgnored nonisolated var ignoredDerived: Int { internalValue }

        init(identifier: String) {
          self.identifier = identifier
        }
      }
      """,
      expandedSource: """
      final class State {
        public private(set) var publicValue = 0
        package var packageValue = 0
        var internalValue = 0
        fileprivate var fileValue = 0
        private var privateValue = 0
        var identifier: String
        let constant = 0
        static var shared = 0
        class var sharedDefault: Int { shared }
        @ObservationIgnored var ignored = 0
        var derived: Int { internalValue }
        @ObservationIgnored nonisolated let ignoredConstant = 0
        @ObservationIgnored nonisolated static var ignoredShared = 0
        @ObservationIgnored nonisolated class var ignoredSharedDefault: Int { ignoredShared }
        @ObservationIgnored nonisolated var ignoredDerived: Int { internalValue }

        init(identifier: String) {
          self.identifier = identifier
        }
      }
      """,
      macros: stateFieldPolicyMacro)
  }

  @Test
  func `Every unsupported State declaration has a precise diagnostic`() {
    assertMacroExpansion(
      """
      @StateFieldPolicy
      final class State {
        final class Reference {}

        var computed: Int {
          get { 0 }
          set {}
        }
        var observed = 0 {
          willSet {}
          didSet {}
        }
        @Wrapped var wrapped = 0
        lazy var delayed = 0
        weak var weakReference: Reference?
        unowned var unownedReference: Reference
        nonisolated var isolatedEscape = 0
        nonisolated(unsafe) var unsafeEscape = 0
        @ObservationIgnored nonisolated var ignoredEscape = 0
        @ObservationIgnored nonisolated(unsafe) var ignoredUnsafeEscape = 0
        var first = 0, second = 0
        var (left, right) = (0, 0)
      }
      """,
      expandedSource: """
      final class State {
        final class Reference {}

        var computed: Int {
          get { 0 }
          set {}
        }
        var observed = 0 {
          willSet {}
          didSet {}
        }
        @Wrapped var wrapped = 0
        lazy var delayed = 0
        weak var weakReference: Reference?
        unowned var unownedReference: Reference
        nonisolated var isolatedEscape = 0
        nonisolated(unsafe) var unsafeEscape = 0
        @ObservationIgnored nonisolated var ignoredEscape = 0
        @ObservationIgnored nonisolated(unsafe) var ignoredUnsafeEscape = 0
        var first = 0, second = 0
        var (left, right) = (0, 0)
      }
      """,
      diagnostics: [
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "writableComputed"),
          message: "writable computed VISOR State field 'computed' is unsupported",
          line: 5,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "accessorObservers"),
          message: "VISOR State field 'observed' cannot declare willSet or didSet",
          line: 9,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "attribute"),
          message: "@Wrapped is unsupported on VISOR State field 'wrapped'",
          line: 13,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "storageModifier"),
          message: "'lazy' is unsupported on VISOR State field 'delayed'",
          line: 14,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "storageModifier"),
          message: "'weak' is unsupported on VISOR State field 'weakReference'",
          line: 15,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "storageModifier"),
          message: "'unowned' is unsupported on VISOR State field 'unownedReference'",
          line: 16,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "isolationModifier"),
          message: "VISOR State field 'isolatedEscape' cannot be declared nonisolated",
          line: 17,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "isolationModifier"),
          message: "VISOR State field 'unsafeEscape' cannot be declared nonisolated(unsafe)",
          line: 18,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "ignoredIsolationModifier"),
          message: "VISOR State field 'ignoredEscape' cannot combine @ObservationIgnored with nonisolated",
          line: 19,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "ignoredIsolationModifier"),
          message: "VISOR State field 'ignoredUnsafeEscape' cannot combine @ObservationIgnored with nonisolated(unsafe)",
          line: 20,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "multipleBindings"),
          message: "declare each VISOR State field in a separate var declaration",
          line: 21,
          column: 3,
          severity: .error),
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "nonIdentifierPattern"),
          message: "VISOR State fields require a single identifier pattern",
          line: 22,
          column: 3,
          severity: .error),
      ],
      macros: stateFieldPolicyMacro)
  }

  @Test
  func `A rejected field suppresses actual ViewModel synthesis`() {
    assertMacroExpansion(
      """
      @MainActor
      @ViewModel
      final class InvalidViewModel {
        final class State {
          var valid = 0
          @ObservationIgnored nonisolated var invalid = 0
        }
      }
      """,
      expandedSource: """
      @MainActor
      final class InvalidViewModel {
        @MainActor @VISOR._ViewModelState
        final class State {
          var valid = 0
          @ObservationIgnored nonisolated var invalid = 0
        }
      }
      """,
      macros: viewModelMacro)
  }

  @Test
  func `A rejected field emits no partial State conformance`() {
    assertMacroExpansion(
      """
      @StateShape
      final class State {
        var valid = 0
        @ObservationIgnored nonisolated(unsafe) var invalid = 0
      }
      """,
      expandedSource: """
      final class State {
        var valid = 0
        @ObservationIgnored nonisolated(unsafe) var invalid = 0
      }
      """,
      diagnostics: [
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "ignoredIsolationModifier"),
          message: "VISOR State field 'invalid' cannot combine @ObservationIgnored with nonisolated(unsafe)",
          line: 4,
          column: 3,
          severity: .error),
      ],
      macros: stateShapeMacro)
  }

  @Test
  func `Bound rejects unsupported placement and declaration`() {
    assertMacroExpansion(
      """
      final class NotAViewModel {
        @Bound(source: \\NotAViewModel.source)
        var value = 0
      }
      """,
      expandedSource: """
      final class NotAViewModel {
        var value = 0
      }
      """,
      diagnostics: [
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "invalidBoundPlacement"),
          message: "@Bound is only supported on a direct member of @ViewModel.State",
          line: 2,
          column: 3,
          severity: .error),
      ],
      macros: sourceEntryMacros)

    assertMacroExpansion(
      """
      @ViewModel
      final class ExampleViewModel {
        final class State {
          @Bound(source: \\ExampleViewModel.source)
          var value: Int { 0 }
        }
      }
      """,
      expandedSource: """
      @ViewModel
      final class ExampleViewModel {
        final class State {
          var value: Int { 0 }
        }
      }
      """,
      diagnostics: [
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "invalidBoundDeclaration"),
          message: "@Bound requires one ordinary stored State property and a source selection",
          line: 4,
          column: 5,
          severity: .error),
      ],
      macros: sourceEntryMacros)
  }

  @Test
  func `Reaction rejects unsupported placement and signature`() {
    assertMacroExpansion(
      """
      @ViewModel
      final class ExampleViewModel {
        @Reaction(source: \\ExampleViewModel.source)
        func changed(_ first: Int, _ second: Int) {}
      }
      """,
      expandedSource: """
      @ViewModel
      final class ExampleViewModel {
        func changed(_ first: Int, _ second: Int) {}
      }
      """,
      diagnostics: [
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "invalidReactionDeclaration"),
          message: "@Reaction requires one nonthrowing Void method parameter and a source selection",
          line: 3,
          column: 3,
          severity: .error),
      ],
      macros: sourceEntryMacros)

    assertMacroExpansion(
      """
      extension ExampleViewModel {
        @Reaction(source: \\ExampleViewModel.source)
        func changed(_ value: Int) {}
      }
      """,
      expandedSource: """
      extension ExampleViewModel {
        func changed(_ value: Int) {}
      }
      """,
      diagnostics: [
        DiagnosticSpec(
          id: MessageID(
            domain: "V11CompileProof",
            id: "invalidReactionPlacement"),
          message: "@Reaction is only supported on a direct @ViewModel member",
          line: 2,
          column: 3,
          severity: .error),
      ],
      macros: sourceEntryMacros)
  }
}
