/// Provides a custom default return value for a method generated by
/// ``GenerateStub(_:)`` or ``GenerateSpy(_:)``.
///
/// - Parameter defaultReturn: The expression returned until a generated
///   implementation closure is configured.
@attached(peer)
public macro DefaultReturn<T>(_ defaultReturn: T) = #externalMacro(
  module: "VISORMacros",
  type: "DefaultValueMacro",
)
