/// Provides a custom default value for a property generated by
/// ``GenerateStub(_:)`` or ``GenerateSpy(_:)``.
@attached(peer)
public macro DefaultValue<T>(_ defaultValue: T) = #externalMacro(
  module: "VISORMacros",
  type: "DefaultValueMacro")
