/// Provides a custom default return value for a method generated by
/// ``GenerateStub(_:)`` or ``GenerateSpy(_:)``.
@attached(peer)
public macro DefaultReturn<T>(_ defaultReturn: T) = #externalMacro(
  module: "VISORMacros",
  type: "DefaultValueMacro")
