//
//  LazyViewModelView.swift
//  VISOR
//
//  Created by Anh Nguyen on 5/2/2026.
//

import SwiftUI

// MARK: - LazyViewModelView

/// A view that lazily initializes a single ViewModel and renders state-driven content.
///
/// Conform via `@LazyViewModel` to get default `loadingView`, `emptyView`, and
/// `errorView(message:)`. You must provide `loadedView(state:)`.
public protocol LazyViewModelView: View {
  associatedtype VM: ViewModel
  associatedtype LoadedContent: View
  associatedtype LoadingContent: View
  associatedtype EmptyContent: View
  associatedtype ErrorContent: View

  var viewModel: VM { get }

  /// Factory method that creates the ViewModel instance.
  ///
  /// Generated by `@LazyViewModel` — do not call manually. The macro-generated
  /// `body` calls this once to initialize the `@State` ViewModel on first render.
  func makeViewModel() -> VM

  @ViewBuilder
  func loadedView(state: VM.State) -> LoadedContent

  @ViewBuilder
  var loadingView: LoadingContent { get }

  @ViewBuilder
  var emptyView: EmptyContent { get }

  @ViewBuilder
  func errorView(message: String) -> ErrorContent
}

extension LazyViewModelView {
  public var loadingView: some View {
    ProgressView()
  }

  public var emptyView: some View {
    ContentUnavailableView("No Content", systemImage: "tray")
  }

  public func errorView(message: String) -> some View {
    ContentUnavailableView(
      "Something Went Wrong",
      systemImage: "exclamationmark.triangle",
      description: Text(message))
  }
}
