import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

// MARK: - StateBindingMacro

/// Marker for synchronous binding action routes generated by `@ViewModel`.
public struct StateBindingMacro: PeerMacro {
  public static func expansion(
    of _: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext,
  ) throws -> [DeclSyntax] {
    let scopes = context.lexicalContext
    guard
      declaration.is(EnumCaseDeclSyntax.self),
      let action = scopes.first?.as(EnumDeclSyntax.self),
      action.name.text == "Action",
      scopes.dropFirst().first?.as(ClassDeclSyntax.self)?
        .attributes.visorContains(named: "ViewModel") == true
    else {
      context.diagnose(Diagnostic(node: Syntax(declaration), message: StateBindingDiagnostic.placement))
      return []
    }
    return []
  }
}

// MARK: - ViewModelStateBindingsMacro

/// Adds route storage only to State types that declare action bindings.
public struct ViewModelStateBindingsMacro: MemberMacro {
  public static func expansion(
    of attribute: AttributeSyntax,
    providingMembersOf declaration: some DeclGroupSyntax,
    conformingTo _: [TypeSyntax],
    in _: some MacroExpansionContext,
  ) throws -> [DeclSyntax] {
    guard
      let state = declaration.as(ClassDeclSyntax.self),
      case .argumentList(let arguments) = attribute.arguments
    else { return [] }
    let fields = arguments.map { $0.expression.trimmedDescription }.joined(separator: ", ")
    let prefix = state.modifiers.stateFieldAccessPrefix
    return ["""
      \(raw: prefix)let _visorStateBindingRoutes: VISOR._StateBindingRoutes<\(raw: state.name.text)>? =
        VISOR._StateBindingRoutes(fields: [\(raw: fields)])
      """]
  }
}
